# Generated by Django 5.0.7 on 2024-07-30 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artisan', '0002_artisan_verified_by_authority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('back_story', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('is_customizable', models.BooleanField()),
                ('dimensions', models.JSONField(default=dict)),
                ('product_details', models.JSONField(default=dict)),
                ('raw_material', models.CharField(choices=[('mango', 'Mango Based Product'), ('banana', 'Banana Based Product'), ('honey', 'Honey Based Product'), ('groundnut', 'Groundnut Based Product'), ('herbs', 'Herbs Based Product'), ('perfume', 'Perfumes Based Product'), ('silk', 'Silk Based'), ('jute', 'Jute Based'), ('leather', 'Leather Based'), ('wool', 'Wool Based'), ('cotton', 'Cotton Based'), ('aloe_vera', 'Aloe Vera based'), ('fabric', 'Fabric Based'), ('ceramic', 'Ceramic Based Artwork'), ('paper', 'Paper Based Artwork'), ('soapstone', 'Soapstone Based Artwork'), ('marble', 'Marble Based Artwork'), ('brass', 'Brass Based Artwork'), ('silver', 'Silver Based Artwork'), ('gold', 'Gold Based Artwork'), ('plastic_stones', 'Plastic Stones Based Artwork'), ('clay', 'Clay Based Handicrafts'), ('wood', 'Wood Based Handicrafts'), ('bamboo', 'Bamboo Based Handicrafts'), ('sikki', 'Sikki Based Handicrafts'), ('plastic', 'Plastic Based Handicrafts')], max_length=50)),
                ('category', models.CharField(choices=[('food', 'Food Product'), ('clothing', 'Clothing Product'), ('artwork', 'Artwork'), ('handicraft', 'Handicraft Product'), ('other', 'Other Products')], max_length=50)),
                ('quantity', models.PositiveBigIntegerField(blank=True, null=True)),
                ('restock_date', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listed_products', to='artisan.artisan')),
            ],
        ),
    ]
