# Generated by Django 5.0.7 on 2024-07-30 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_tax_percent_productlineitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductLineItem',
        ),
    ]
