# Generated by Django 5.0.7 on 2024-08-17 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_delete_productlineitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='custom_note',
        ),
    ]
