# Generated by Django 5.0.7 on 2024-08-17 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_remove_jobpostapplicationrequest_is_confirmed_and_more'),
        ('product', '0005_remove_product_custom_note'),
        ('services', '0002_orderreview'),
        ('workshop', '0002_event_is_active_workshop_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='RentalMachineImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rental_machines/')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_images', to='community.rentalmachine')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='workshops/')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_images', to='workshop.workshop')),
            ],
        ),
    ]
