# Generated by Django 5.0.7 on 2024-07-30 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0002_artisan_verified_by_authority'),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPostApplicationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applied_jobs', to='artisan.artisan')),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_requests', to='community.jobpost')),
            ],
        ),
        migrations.CreateModel(
            name='RentalMachineBookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('purpose', models.TextField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booked_machines', to='artisan.artisan')),
                ('rental_machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_requests', to='community.rentalmachine')),
            ],
        ),
    ]
