# Generated by Django 5.0.7 on 2024-08-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_remove_jobpostapplicationrequest_is_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalmachine',
            name='rate',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
