# Generated by Django 4.1.13 on 2024-07-28 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artisan',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.baseuser')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('address', models.TextField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=15, null=True)),
                ('aadhar_image', models.ImageField(upload_to='artisan/aadhar/')),
                ('pan_number', models.CharField(blank=True, max_length=15, null=True)),
                ('pan_image', models.ImageField(upload_to='artisan/panCard/')),
            ],
            options={
                'verbose_name': 'Artisan',
                'verbose_name_plural': 'Artisans',
            },
            bases=('user.baseuser',),
        ),
    ]
