# Generated by Django 5.0.7 on 2024-08-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0002_artisan_verified_by_authority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisan',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='artisan',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
