# Generated by Django 5.0.7 on 2024-08-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
