# Generated by Django 5.0.7 on 2024-08-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_event_is_active_workshop_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='organized_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
