# Generated by Django 5.0.7 on 2024-08-17 15:07

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_baseuser_valid_otp_alter_baseuser_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseuser',
            options={'verbose_name': 'Base User', 'verbose_name_plural': 'Base Users'},
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[user.models.validate_phone_number]),
        ),
    ]
