# Generated by Django 5.0.7 on 2024-08-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_baseuser_options_alter_baseuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as active.'),
        ),
    ]
