# Generated by Django 5.0.7 on 2024-07-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('CON', 'Confirmed'), ('SHP', 'Shipped'), ('DLV', 'Delivered'), ('RFI', 'Refund Initiated'), ('RFP', 'Refund In Process'), ('RFS', 'Refund Successs'), ('RFC', 'Refund Cancelled'), ('CAN', 'Cancelled')], default='PEN', max_length=50),
        ),
    ]
