# Generated by Django 5.0.7 on 2024-07-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_order_estimate_delivery_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(choices=[('ONLINE', 'UPI / Gpay / Cards'), ('COD', 'Cash on Delivery'), ('UNSET', 'Unset')], default='UNSET', max_length=15),
            preserve_default=False,
        ),
    ]
